### ISSUE TITLE
Use HTML in list items

### ISSUE THREAD

**Issue by daniellimws** [orppra/ropa#24]
Allow for better styling capabilities.

**Comment by daniellimws** [comment]
Maybe a template that can be used with format strings

**Comment by jeffsieu** [comment]
This is already possible using QString?

**Comment by jeffsieu** [comment]
Or do you mean add some kind of syntax highlighting/basic styling to the gadgets?

**Comment by daniellimws** [comment]
Yea instead of some shitty newline, use <p>

**Comment by daniellimws** [comment]
and have different alignments also
