### ISSUE TITLE
Prompt user when no file is loaded

### ISSUE THREAD

**Issue by daniellimws** [orppra/ropa#26]

**Comment by jeffsieu** [comment]
When should this be done?

**Comment by daniellimws** [comment]
When the user clicks on any of the search buttons before loading a binary

**Comment by jeffsieu** [comment]
Or should we simply disable all the buttons? Or even replace the whole inner part with something like "Start a new project or open an existing one"?

**Comment by daniellimws** [comment]
Both also can, you decide lol

**Comment by jeffsieu** [comment]
Okay, I'll disable the buttons.

**Comment by daniellimws** [comment]
Create SearchButtonController for the 3 buttons to extend from

**Comment by daniellimws** [comment]
Actually, magically fixed with #78
