### ISSUE TITLE
Gadget items duplicated when dragging item back into gadgets list

### ISSUE THREAD

**Issue by daniellimws** [orppra/ropa#33]
To reproduce:
Drag a gadget item into the gadget list itself

Should see a duplicated gadget item

**Comment by jeffsieu** [comment]
Should we allow for gadgets to be dragged into the gadget list?

**Comment by daniellimws** [comment]
No, what's the point lol

**Comment by daniellimws** [comment]
Should be just a catalog to choose thing from.
