### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by daniellimws** [orppra/ropa#41]
Do we want to add GPL License onto the top of every file?

**Comment by jeffsieu** [comment]
Yeah I think we can

**Comment by jeffsieu** [comment]
@jeffsieu Or should we consider other licenses?

**Comment by daniellimws** [comment]
@jeffsieu Like what? I've previously considered and thought that this shld be fine for us.

**Comment by jeffsieu** [comment]
@daniellimws I thought we were using MIT license?

**Comment by daniellimws** [comment]
@jeffsieu Can but what's the rationale?
