### ISSUE TITLE
FileDialog controller or utils?

### ISSUE THREAD

**Issue by daniellimws** [orppra/ropa#59]
Currently we have FileDialogController, but a FileDialogUtils sounds more appropriate. But at the same time, FileDialog is also related to the gui, so doesn't sound good to move it entirely to the utils module.

I suggest keeping the gui related parts in FileDialogController, while more logic related parts to be moved into FileDialogUtils.

**Comment by daniellimws** [comment]
Or rather FileDialogService

**Comment by daniellimws** [comment]
Do you think we need a Service superclass? Feels that it's gonna be empty anyways.

**Comment by Enigmatrix** [comment]
@daniellimws nooo nothing in common
